apiVersion: v1
kind: ConfigMap
metadata:
  name: fcg-users-config
data:
  NEW_RELIC_APP_NAME: "${APM_SERVICE_NAME}"
  NewRelic__Enabled: "${NEW_RELIC_ENABLED}"
  NewRelic__Endpoint: "${NEW_RELIC_ENDPOINT}"
  AspNetCore_Environment: "${ENV}"
  ElasticApm__Enabled: "${ELASTIC_APM_ENABLED}"
  ElasticApm__ServerUrl: "${ELASTIC_APM_SERVER_URL}"
  ElasticApm__ServiceName: "${APM_SERVICE_NAME}"
  ElasticApm__Environment: "${ENV}"