apiVersion: v1
kind: ConfigMap
metadata:
  name: fcg-users-config
data:
  NEW_RELIC_APP_NAME: "${NEW_RELIC_APP_NAME}"
  NewRelic__Enabled: "${NEW_RELIC_ENABLED}"
  NewRelic__Endpoint: "${NEW_RELIC_ENDPOINT}"
  AspNetCore__Environment: "${ENVIRONMENT}"