apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fcg-users-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fcg-users

  minReplicas: 2
  maxReplicas: 5
  
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75

  behavior:
    scaleUp:
      stabilizationWindowSeconds: 120   # tempo para estabilização antes de aumentar réplicas
      policies:                         # políticas de aumento
      - type: Percent                   # política baseada em porcentagem
        value: 50                       # aumenta no máximo 50% das réplicas atuais por período
        periodSeconds: 60               # período de 60 segundos
    scaleDown:
      stabilizationWindowSeconds: 120   # tempo para estabilização antes de reduzir réplicas
      policies: 
      - type: Pods                      # política de redução baseada em número de pods
        value: 1                        # reduz no máximo 1 pod por período
        periodSeconds: 60               # período de 60 segundos

